### ISSUE TITLE
Leap year

### ISSUE THREAD

**Issue by kuenishi** [nagataaaas/Japanera#2]
すごいライブラリですね！もともと生で`datetime.datetime.strptime()` を使っていたのですが、困ったことがあったのでライブラリを探しているところでした。 `datetime.strptime()` は西暦でちゃんと入れないと閏年の扱いに失敗するみたいです。なので、以下の挙動もバグだと思います。

```python
Python 3.8.2 (default, Feb 27 2020, 19:58:50) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import japanera
>>> janera = japanera.Japanera()
>>> janera.strptime("令和02年02月01日", "%-E%-O年%m月%d日")
[datetime.datetime(2020, 2, 1, 0, 0)]
>>> janera.strptime("令和02年02月29日", "%-E%-O年%m月%d日")
[]
```
`datetime` はこうなります。
```python
>>> from datetime import datetime
>>> datetime.strptime("R02.02.29", "R%y.%m.%d")              
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 534, in _strptime
    julian = datetime_date(year, month, day).toordinal() - \
ValueError: day is out of range for month
>>> 
```

**Comment by nagataaaas** [comment]
ありがとうございます。長い間気づかずすみません。
一旦strptimeでパースしていることで、年号が指定されていても数字の部分がうるう年判定のルールに当てはまっていないと正しくパースできていないようでした。
パーサの部分を追加したので、これで大丈夫なはずです。

ありがとうございました。
