### ISSUE TITLE
[Python 3.8.10] Type error on any function called

### ISSUE THREAD

**Issue by SeasonedMiso** [nagataaaas/Japanera#8]
```Traceback (most recent call last):
  File "date.py", line 13, in <module>
    era_of_1950_1_1: Era = EraDate(1950, 1, 1).era
  File "/home/miso/.local/lib/python3.8/site-packages/japanera/japanera.py", line 157, in __new__
    result = find_era_and_date(absolute_year=year, month=month, day=day)
  File "/home/miso/.local/lib/python3.8/site-packages/japanera/parser.py", line 484, in find_era_and_date
    _found = find_eras_with_year(absolute_year)
  File "/home/miso/.local/lib/python3.8/site-packages/japanera/parser.py", line 562, in find_eras_with_year
    def _find_first_era_after_year_index(era_list: list["Era"]) -> int:
TypeError: 'type' object is not subscriptable```

**Comment by SeasonedMiso** [comment]
Using Ubuntu WSL in windows 10

**Comment by nagataaaas** [comment]
Sorry that I didn't notice that this issue have been created.
I'll fix this problem ASAP
